name: capture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.3.2
  logger: ^2.0.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  extended_image: ^8.1.1
  formz: ^0.6.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  go_router: ^10.1.2
  flutter_native_splash: ^2.2.16
  responsive_framework: ^1.1.1
  dropdown_search: ^5.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  bloc_concurrency: ^0.2.2
  flutter_dotenv: ^5.1.0
  lottie: ^2.6.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/